### ISSUE TITLE
Guide for noob

### ISSUE THREAD

**Issue by 0x0L** [Mikrocontroller-net/transistortester#2]
Hello,

Thanks for this cool project!

I recently bought an LCR T4 and was really hopping to be able to upgrade the firmware using an Arduino Nano.
Is this something that's do-able or do I need some other card or even a dedicated usb programmer ?

Many thanks

**Comment by kubi48** [comment]
Hallo,

 

there are two versions of this T4 tester that differ in the display connection.

You can find precompiled hex and eep files in the

directories Software/trunk/mega328_T3_T4_st7565 and Software/trunk/Mega328_T4_v2_st7565.

 

Of course you can use a Arduino Nano or Arduino UNO to update the T4 Tester with the

ISP-Programmer sample application.


But you can use also a USBASP AVR programmer  with a 10pin to 6-pin adapter or a

Pololu USB AVR Programmer, which has a additional USB-serial interface at the

same board.

 

Please note, that the standard configuration of the open source Software enables

the SamplingADC feature of Pieter-Tjerk.

With that feature the tester can measure small coils too,

if you connect a capacitor (10nf - 30nF) parallel to build a resonant circuit.

For this purpose, the calibration process was expanded to include the measurement of this capacitor.

Please use a high quality capacitor for this feature (low inductance capacitor)

to get proper inductance measurements.

 

There are some helpfull scripts too install the Transistortester Software

with Linux (tested with Linux Mint) at

github.com/kubi48/TransistorTester-Linux-install

 

Best regards,

Kark-Heinz

 

Gesendet: Freitag, 07. Mai 2021 um 12:41 Uhr
Von: "nullptr" ***@***.***>
An: "Mikrocontroller-net/transistortester" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [Mikrocontroller-net/transistortester] Guide for noob (#2)


 

Hello,

Thanks for this cool project!

I recently bought an LCR T4 and was really hopping to be able to upgrade the firmware using an Arduino Nano.
Is this something that's do-able or do I need some other card or even a dedicated usb programmer ?

Many thanks

**Comment by 0x0L** [comment]
Thank you very much for your answers!
Best regards
